### ISSUE TITLE
how can I get some files like identity_CelebA.

### ISSUE THREAD

**Issue by suwoncjh** [foamliu/FaceNet#2]
Hi, thank you for sharing your great code.

but when I try to execute your code, there are some problems that there is no file like identity_CelebA.txt, list_bbox_celeba.

where can I get those files?

**Comment by dnahid** [comment]
@suwoncjh Visit [http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html]. You may email the data owner for the identity text file.

**Comment by JasonLee925** [comment]
I think you can just download them on their google drive.

**Comment by suwoncjh** [comment]
@dnahid , @JasonLee925 Thanks.
